use_case: mountain_tamer
dependencies:
  - gymnasium[classic_control]

environment:
  name: Mountain car TAMER
  description: ""
  filepaths:
    environment: mountain_tamer/environment.py

policy:
  name: Mountain car TAMER
  description: ""
  filepaths:
    policy: mountain_tamer/policy.py
    tamer: mountain_tamer/tamer.py
  checkpoint_interval: 1

agents:
  - role: agent_mct
    name: Mountain car TAMER agent
    description: ""
    policy: Mountain car TAMER
    participant: true
    keyboard_inputs:
      ArrowUp: 1
      ArrowDown: -1
      default: 0
    keyboard_input_display:
      ArrowUp:
        symbol: "\u2191"
        label: Good
      ArrowDown:
        symbol: "\u2193"
        label: Bad
    multiple_keyboard_inputs: false
    inputs_type: reward
    textual_inputs: false

experiment:
  link: mountain_tamer
  name: Mountain car TAMER
  short_description: TAMER mountain care experiment by Knox & Stone
  long_description: This is a classic experiment by Knox & Stone in which an agent is trained with evaluative feedback.
  enabled: true
  number_of_episodes: 50
  target_fps: 6.666
  wait_for_inputs: false