use_case: amaze
dependencies:
  - amaze-benchmarker[all]
  - gymnasium
  - scikit-learn

environment:
  name: Amaze
  description: A lightweight maze navigation task generator for sighted AI agents
  filepaths:
    environment: amaze/environment.py

policy:
  name: Amaze
  description: TAMER policy for Amaze
  filepaths:
    policy: amaze/policy.py
    tamer: amaze/tamer.py
  checkpoint_interval: 1

agents:
  - role: amaze_agent_0
    name: Amaze agent
    description: ""
    policy: Amaze
    participant: true
    keyboard_inputs:
      ArrowUp: 1
      ArrowDown: -1
      default: 0
    keyboard_input_display:
      ArrowUp:
        symbol: "\u2191"
        label: Good
      ArrowDown:
        symbol: "\u2193"
        label: Bad
    multiple_keyboard_inputs: false
    inputs_type: reward
    textual_inputs: false

experiment:
  link: amaze
  name: Amaze
  short_description: A lightweight maze navigation task
  long_description: A lightweight maze navigation task generator for sighted AI agents.
  enabled: true
  number_of_episodes: 1
  target_fps: 1.0
  wait_for_inputs: true